import Link from 'next/link';
import {CareVideo} from '@/components/care-video';
import {AgentObservatory} from '@/components/agent-observatory';
import {DemoWorkspace} from '@/components/demo-workspace';
import {ContactForm} from '@/components/contact-form';
const benefits=[['01','Less worry.','A protection plan designed around the hardware you actually use.'],['02','A clear next step.','One place to start when a machine needs attention.'],['03','Care that keeps up.','From your first deployment to a growing fleet.']];
export default function Home(){return <>
<section className="landscape-hero"><div className="hero-atmosphere" aria-hidden="true"/><div className="landscape-copy shell"><p className="eyebrow">CARE FOR THE PHYSICAL WORLD</p><h1>Extraordinary machines.<br/><span>Everyday peace of mind.</span></h1><p className="lede">Protection and care for robotics, hardware and physical AI.<br/>So you can keep building what’s next.</p><div className="actions"><Link href="/#contact" className="button primary">Get early access <span>↗</span></Link><Link href="/demo" className="button hero-secondary">Build your care program <span>→</span></Link></div></div><div className="landscape-bottom shell"><span>HARDWARE MOVES THE WORLD.<br/>WE’RE HERE TO LOOK AFTER IT.</span><span>ROBOTICS · HARDWARE · PHYSICAL AI</span><a href="#care">Explore ↓</a></div></section>
<div className="category-strip"><div className="shell"><span>A little care goes a long way.</span><b>Robotics</b><i>✳</i><b>Intelligent hardware</b><i>✳</i><b>Physical AI</b></div></div>
<section className="section shell"><div className="section-heading"><p className="eyebrow">MEET HARDSURANCE CARE</p><h2>Complex machines.<br/><span>Refreshingly simple care.</span></h2><p>You shouldn’t need to become a hardware expert when something goes wrong. We’re building a simpler way to protect your equipment and find a path back to work.</p></div><div className="benefit-grid">{benefits.map(([n,t,d])=><article key={n}><span className="index">{n} /</span><h3>{t}</h3><p>{d}</p></article>)}</div></section>
<section className="section mint-section" id="care"><div className="shell care-split"><div><p className="eyebrow">FROM FIRST DAY TO WHAT’S NEXT</p><h2>It’s hardware.<br/>Life happens.</h2><p>A stalled motor. A damaged sensor. A machine that just won’t start. Hardsurance is being built to make the next step feel a lot less complicated.</p><Link className="text-link" href="/product">Meet your care plan <span>↗</span></Link></div><div className="coverage-stack">{[['✳','Protection, made personal','Start with your machine, its environment and how you use it.'],['↗','A route to repair','Bring the issue, asset details and service updates into one place.'],['+','Room to grow','Keep care organized as you add devices, sites and teams.']].map(([i,t,d])=><article key={t}><span className="feature-icon">{i}</span><div><h3>{t}</h3><p>{d}</p></div></article>)}<p className="fine-print">Early access. Final plan benefits and service availability are still being developed.</p></div></div></section>
<section className="section shell" id="machines"><div className="section-heading row"><div><p className="eyebrow">MADE FOR THE PHYSICAL WORLD</p><h2>Different machines.<br/>The same need for care.</h2></div><p>From moving parts to the infrastructure behind intelligence. Explore the environments shaping what we’re building.</p></div><div className="machine-grid">{[['robotics','Robotics','For the machines working alongside us.','robot-chess'],['drones','Field hardware','For intelligence beyond the lab.','industrial-site'],['data-centers','AI infrastructure','For the hardware behind every answer.','data-center'],['space','Frontier systems','For ambitions beyond the ordinary.','orbital'],['ai-chips','Silicon & AI chips','For the silicon powering the next generation of intelligence.','ai-chips']].map(([slug,t,d,f],i)=><article className="machine-card" key={slug}><CareVideo src={`/films/${f}.mp4`} label={t}/><div><span className="eyebrow">0{i+1} / BUILT FOR MORE</span><h3><Link href={`/use-cases/${slug}`}>{t} <span>↗</span></Link></h3><p>{d}</p></div></article>)}</div></section>
<AgentObservatory/>
<section className="studio-showcase" id="studio"><div className="shell"><div className="section-heading row"><div><p className="eyebrow">YOUR BRAND. YOUR CARE PROGRAM.</p><h2>An AppleCare-like experience.<br/><span>With your name on it.</span></h2></div><p>From your brand to your benefits to your customer portal. See how Hardsurance could bring your white-label care program to life.</p></div><div className="studio-frame"><DemoWorkspace compact/></div><div className="studio-showcase-foot"><span>Interactive preview. Sample plans. No signup.</span><Link className="text-link" href="/demo">Open the full workspace ↗</Link></div></div></section>
<section className="section shell story-section"><div className="section-heading row"><div><p className="eyebrow">HARDWARE HAS COME A LONG WAY</p><h2>Its care should, too.</h2></div><p>From the first tools to machines that think and move. A new generation of hardware deserves a new generation of care.</p></div><CareVideo src="/films/hardsurance-stone-to-station.mp4" label="The evolution of hardware from stone tools to space stations"/><div className="story-caption"><span>A SHORT FILM / THE HARDWARE STORY</span><Link href="/company">Why we’re building Hardsurance ↗</Link></div></section>
<section id="contact" className="contact-section"><div className="shell care-split"><div><p className="eyebrow">LET’S BUILD BETTER CARE</p><h2>The next big thing.<br/>With a little backup.</h2><p>Building hardware? Running a fleet? Tell us what you’re working on and help shape Hardsurance Care.</p><a className="text-link" href="mailto:contact@hardsurance.com">contact@hardsurance.com ↗</a></div><ContactForm/></div></section></>}
