import Link from 'next/link';
import {CareVideo} from '@/components/care-video';
import {DemoWorkspace} from '@/components/demo-workspace';
import {AgentObservatory} from '@/components/agent-observatory';
import {FlowerWalkthrough} from '@/components/flower-walkthrough';
import {ContactForm} from '@/components/contact-form';
const benefits=[['01','Equipment-specific protection','Proposed protection options informed by equipment type, operating conditions and intended use.'],['02','Coordinated service','A structured process for reporting issues, reviewing eligibility and coordinating the next service step.'],['03','Lifecycle visibility','An organized record of equipment, plan details and service activity as your deployment expands.']];
export default function Home(){return <>
<section className="landscape-hero"><div className="hero-atmosphere" aria-hidden="true"/><div className="landscape-copy shell"><p className="eyebrow">CARE FOR THE PHYSICAL WORLD</p><h1>Advanced hardware.<br/><span>Comprehensive care.</span></h1><p className="lede">Hardsurance Care brings protection planning, service coordination and asset management together for robotics, hardware and physical AI.</p><div className="actions"><Link href="/#contact" className="button primary">Request early access <span>↗</span></Link><Link href="/demo" className="button hero-secondary">Explore Care Studio <span>→</span></Link></div></div></section>
<section className="section shell story-section"><div className="section-heading row"><div><p className="eyebrow">THE EVOLUTION OF HARDWARE</p><h2>From stone tools.<br/>To autonomous systems.</h2></div><p>Hardware has evolved from stone tools to autonomous, AI-powered systems. Insurance and hardware care should reflect that progress, rather than remain anchored to the past.</p></div><CareVideo featured autoPlay src="/films/hardsurance-stone-to-station.mp4" label="The evolution of hardware from stone tools to space stations"/></section>
<div className="category-strip"><div className="shell"><span>One approach to hardware care.</span><b>Robotics</b><i>✳</i><b>Intelligent hardware</b><i>✳</i><b>Physical AI</b></div></div>
<section className="section shell centered-benefits"><div className="section-heading"><p className="eyebrow">MEET HARDSURANCE CARE</p><h2>Hardware care.<br/><span>Clearly structured.</span></h2><p>We are developing a coordinated care experience for equipment owners and manufacturers: defined protection options, organized service requests and a consistent record throughout the hardware lifecycle.</p></div><div className="benefit-grid">{benefits.map(([n,t,d])=><article key={n}><span className="index">{n} /</span><h3>{t}</h3><p>{d}</p></article>)}</div></section>
<section className="section mint-section" id="care"><div className="shell care-split"><div><p className="eyebrow">PROTECTION THROUGHOUT THE LIFECYCLE</p><h2>A defined process.<br/>When equipment needs care.</h2><p>Autonomous machines and AI-enabled hardware combine mechanical components, electronics, sensors and software. When equipment fails or is damaged, Hardsurance Care is being designed to connect these dependencies with equipment records, plan review and a coordinated service process.</p><Link className="text-link" href="/product">Explore the care approach <span>↗</span></Link></div><div className="coverage-stack">{[['✳','Protection aligned with use','Define equipment, deployment conditions and service requirements before reviewing suitable plan options.'],['↗','Structured service assessment','Record the issue, assess it against the agreed terms and document the proposed service route.'],['+','Fleet and deployment management','Maintain consistent equipment records across additional devices, locations and teams.']].map(([i,t,d])=><article key={t}><span className="feature-icon">{i}</span><div><h3>{t}</h3><p>{d}</p></div></article>)}<p className="fine-print">Early access. Final plan benefits and service availability are still being developed.</p></div></div></section>
<section className="section shell" id="machines"><div className="section-heading row"><div><p className="eyebrow">MADE FOR THE PHYSICAL WORLD</p><h2>Specialized equipment.<br/>A consistent care framework.</h2></div><p>We are evaluating care requirements across these hardware categories. Eligibility and service availability will be determined for each equipment type and deployment. <Link className="text-link" href="/hardware">Explore all hardware categories →</Link></p></div><div className="machine-grid">{[['robotics','Robotics','Autonomous platforms, robotic systems and industrial automation.','robot-chess'],['drones','Field hardware','Deployed sensors, connected devices and field equipment.','industrial-site'],['data-centers','AI infrastructure','Compute systems, cooling equipment and supporting infrastructure.','data-center'],['space','Frontier systems','Advanced systems with specialized lifecycle and service requirements.','orbital'],['ai-chips','Silicon & AI chips','Accelerators, processors and embedded compute components.','ai-chips'],['autonomous','Autonomous hardware','Autonomous vehicles, mobile platforms and navigation-enabled systems.','autonomous-hardware']].map(([slug,t,d,f],i)=><article className="machine-card" key={slug}><CareVideo src={`/films/${f}.mp4`} label={t}/><div><span className="eyebrow">0{i+1} / HARDWARE CATEGORY</span><h3><Link href={`/use-cases/${slug}`}>{t} <span>↗</span></Link></h3><p>{d}</p></div></article>)}</div></section>

<section className="studio-showcase" id="studio"><div className="shell"><div className="section-heading row"><div><p className="eyebrow">CARE PROGRAMS FOR MANUFACTURERS</p><h2>Your hardware.<br/><span>A care program under your brand.</span></h2></div><p>Configure a sample branded program, review proposed benefits and explore the customer enrollment and service experience in Care Studio.</p></div><FlowerWalkthrough/><div className="studio-frame"><DemoWorkspace compact/></div><div className="studio-showcase-foot"><span>Interactive preview. Sample plans. No signup.</span><Link className="text-link" href="/demo">Open the full workspace ↗</Link></div></div></section>

<AgentObservatory/>
<section id="contact" className="contact-section"><div className="shell care-split"><div><p className="eyebrow">REQUEST EARLY ACCESS</p><h2>Discuss your hardware.<br/>Define your care requirements.</h2><p>Share your equipment category, deployment size and service requirements. Our team will contact you to discuss early access and potential program suitability.</p><a className="text-link" href="mailto:contact@hardsurance.com">contact@hardsurance.com ↗</a></div><ContactForm/></div></section></>}
