'use client';
import {BrandMark} from '@/components/brand-mark';
import {useEffect,useRef,useState} from 'react';
import {saveCareBrief} from '@/lib/care-brief';
import Link from 'next/link';
import {agentScenarios} from '@/lib/agent-scenarios';

export function AgentObservatory(){
 const [scenarioId,setScenarioId]=useState('robotics');
 const [view,setView]=useState('map');
 const [tick,setTick]=useState(0);
 const [playing,setPlaying]=useState(true);
 const [visible,setVisible]=useState(false);
 const [selected,setSelected]=useState('motor');
 const [query,setQuery]=useState('');
 const [filter,setFilter]=useState('All signals');
 const [reviewed,setReviewed]=useState<string[]>([]);
 const [speed,setSpeed]=useState(1);
 const [company,setCompany]=useState('Atlas Robotics');
 const total=10;
 const stages=['Map the incident','Design the care','Assemble your program','Prepare the handoff'];
 const stage=tick<6?0:tick<8?1:tick<10?2:3;
 function handoff(){saveCareBrief({source:'Agent workspace simulation',company,program:`${company.trim()||'Your brand'} Care+`,hardware:scenario.name,summary:`Sample care program for ${scenario.asset}. ${shown.length} signals mapped; ${reviewed.length} checks reviewed in the demo. Suggested scope: hardware faults, repair coordination and replacement assessment. Diagnosis, eligibility, pricing and final terms require review.`})}
 const root=useRef<HTMLDivElement>(null);
 const scenario=agentScenarios.find(s=>s.id===scenarioId)!;
 const findings=scenario.findings;
 const shown=findings.slice(0,Math.min(tick,findings.length));
 const finding=findings.find(f=>f.id===selected)!;
 const matches=shown.filter(f=>(filter!=='Needs review'||f.severity==='review')&&`${f.label} ${f.agent} ${f.signal}`.toLowerCase().includes(query.toLowerCase()));
 const completed=tick>=total;
 useEffect(()=>{if(window.matchMedia('(prefers-reduced-motion: reduce)').matches)setPlaying(false);const observer=new IntersectionObserver(([entry])=>setVisible(entry.isIntersecting),{threshold:.1});if(root.current)observer.observe(root.current);return()=>observer.disconnect()},[]);
 useEffect(()=>{if(!playing||!visible||completed)return;const timer=setInterval(()=>setTick(t=>Math.min(t+1,total)),2200/speed);return()=>clearInterval(timer)},[playing,visible,completed,speed,findings.length]);
 function restart(id=scenarioId){setScenarioId(id);setTick(0);setSelected('motor');setReviewed([]);setQuery('');setFilter('All signals')}
 function selectNode(id:string){setSelected(id)}
 return <section className="agent-section" id="agents"><div className="shell"><div className="section-heading row"><div><p className="eyebrow">INTELLIGENCE BEHIND THE CARE</p><h2>Complex problems.<br/><span>A connected picture.</span></h2></div><p>Watch specialist agents map a hardware incident, connect the evidence and prepare the next checks. Explore every connection yourself.</p></div></div><div className={`agent-landscape ${playing&&!completed?'agents-running':''} ${view==='checks'?'landscape-checks':''}`}><div className="agent-app" ref={root}>
 <div className="agent-browser"><span className="agent-grip" aria-hidden="true">⠿</span><span className="agent-home"><BrandMark/></span><span className="agent-url">Care Intelligence <span aria-hidden="true"> / </span> {view==='map'?'Explore the problem':'Review the evidence'}</span><span className="agent-demo-label">SIMULATION</span></div>
 <div className="agent-toolbar"><label className="agent-scenario">Scenario<select value={scenarioId} onChange={e=>restart(e.target.value)}>{agentScenarios.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><div className="agent-playback"><button onClick={()=>{if(completed){restart();setPlaying(true)}else setPlaying(!playing)}} aria-label={completed?'Replay agent simulation':playing?'Pause agent simulation':'Play agent simulation'}>{completed?'↺ Replay':playing?'Ⅱ Pause':'▷ Play'}</button><button onClick={()=>setTick(t=>Math.min(t+1,total))} disabled={completed}>Step →</button><button onClick={()=>restart()} aria-label="Restart agent simulation">↺ Reset</button><button onClick={()=>setSpeed(speed===1?2:1)} aria-label={`Playback speed ${speed} times`}>{speed}×</button></div></div>
 <div className="agent-journey" aria-label="Care program progress">{stages.map((label,i)=><div key={label} className={stage===i?'current':stage>i?'done':''}><span>{stage>i?'✓':`0${i+1}`}</span><b>{label}</b></div>)}</div><div className="agent-tabs" aria-label="Agent workspace views"><button aria-pressed={view==='map'} onClick={()=>setView('map')}>⌘ Problem map</button><button aria-pressed={view==='checks'} onClick={()=>setView('checks')}>☷ Care-plan checks</button><span>{scenario.asset}</span></div>
 <div className="agent-roster">{[...findings.map(f=>({name:f.agent.replace('.agent',''),id:f.id})),{name:'benefits',id:'benefits'},{name:'brand',id:'brand'},{name:'experience',id:'experience'},{name:'handoff',id:'handoff'}].map((a,i)=><button key={a.id} disabled={i>=6||i>=tick} onClick={()=>selectNode(a.id)} className={i<tick?'finished':i===tick&&playing?'working':''}><i/><b>{a.name}</b><small>{i<tick?'Draft ready':i===tick&&playing?'Working…':'Queued'}</small></button>)}</div><div className="signal-strip" aria-label={`${shown.length} of ${findings.length} sample signals mapped`}>{Array.from({length:48},(_,i)=><i key={i} className={i<tick*8?'signal-active':''} style={{height:10+(i*7%19)}}/>)}</div>
 <div className="agent-main"><aside className="trace-panel"><div className="panel-heading"><span>{view==='map'?'AGENT ACTIVITY':'MAPPED FINDINGS'}</span><b><i/>{completed?'COMPLETE':playing?'RUNNING':'PAUSED'}</b></div><div className="trace-search"><input aria-label="Search mapped signals" placeholder="Search signals or agents…" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Filter mapped signals" value={filter} onChange={e=>setFilter(e.target.value)}><option>All signals</option><option>Needs review</option></select></div><div className="trace-list">{matches.length===0?<div className="trace-empty">{tick===0?<><span>◎</span><b>Ready to connect the dots.</b><p>Press Step to inspect one signal, or play the simulation.</p></>:<><b>No matching signals.</b><p>Try another search or filter.</p></>}</div>:[...matches].reverse().map(f=><button key={f.id} className={`trace-row ${f.severity} ${selected===f.id?'trace-selected':''}`} onClick={()=>selectNode(f.id)}><div><time>00:{String((findings.indexOf(f)+1)*3).padStart(2,'0')}</time><b>{f.agent}</b><span>{f.severity==='review'?'REVIEW':f.severity==='ready'?'MATCH':'LINK'}</span></div><strong>{f.label}</strong><p>{f.signal}</p></button>)}</div><div className="trace-summary"><span>{shown.length} signals mapped</span><span>{shown.filter(f=>f.severity==='review').length} need review</span></div></aside>
 <div className="agent-canvas"><div className="panel-heading"><span>{view==='map'?'DEPENDENCY MAP':'CHECKS PREPARED FROM FINDINGS'}</span><b>{view==='map'?`${shown.length} CONNECTED`:`${reviewed.length} / ${shown.length} REVIEWED`}</b></div>{view==='map'?<><div className="graph-stage"><svg viewBox="0 0 600 420" preserveAspectRatio="none" aria-hidden="true">{shown.map(f=><path key={f.id} className={`graph-edge ${selected===f.id?'edge-selected':''}`} d={`M300 210 Q${f.x*6} 210 ${f.x*6} ${f.y*4.2}`}/>)}{shown.length>=4&&<path className="graph-edge graph-edge-secondary" d="M138 118 Q290 30 438 97 Q555 200 474 277"/>}</svg><div className="graph-core"><span><BrandMark/></span><b>Care intelligence</b><small>{scenario.name}</small></div>{findings.map((f,i)=><button key={f.id} className={`graph-node ${f.severity} ${i<tick?'node-visible':'node-pending'} ${selected===f.id&&i<tick?'node-selected':''}`} style={{left:`${f.x}%`,top:`${f.y}%`}} disabled={i>=tick} aria-label={`Inspect ${f.label}`} aria-pressed={selected===f.id&&i<tick} onClick={()=>selectNode(f.id)}><span>{f.short}</span><b>{f.label}</b><small>{i<tick?(f.severity==='review'?'Needs review':f.severity==='ready'?'Record matched':'Dependency found'):'Waiting for signal'}</small></button>)}</div><div className="graph-legend"><span><i className="legend-review"/>Needs review</span><span><i className="legend-watch"/>Dependency</span><span><i className="legend-ready"/>Matched record</span></div></>:<div className="checks-table">{shown.length===0?<div className="trace-empty"><b>No checks yet.</b><p>Play or step through a scenario to prepare checks.</p></div>:shown.map((f,i)=><button key={f.id} className={selected===f.id?'check-selected':''} onClick={()=>selectNode(f.id)}><span>C0{i+1}</span><div><b>{f.label}</b><small>{f.check}</small></div><em>{reviewed.includes(f.id)?'REVIEWED':'DRAFT'}</em><span>↗</span></button>)}</div>}</div></div>
 <div className="finding-detail">{tick>findings.findIndex(f=>f.id===selected)?<><div className="finding-title"><span className={`finding-symbol ${finding.severity}`}>{finding.short}</span><div><span className="agent-mono">{finding.agent} / SELECTED FINDING</span><h3>{finding.label}</h3></div><button onClick={()=>setView(view==='map'?'checks':'map')}>{view==='map'?'Inspect care check →':'Show in map →'}</button></div><div className="finding-columns"><div><span>SAMPLE EVIDENCE</span><p>{finding.evidence}</p></div><div><span>{view==='map'?'SUGGESTED NEXT STEP':'CHECK TO PERFORM'}</span><p>{view==='map'?finding.action:finding.check}</p>{view==='checks'&&<button className="review-check" onClick={()=>setReviewed(reviewed.includes(finding.id)?reviewed.filter(id=>id!==finding.id):[...reviewed,finding.id])}>{reviewed.includes(finding.id)?'✓ Reviewed in this demo · undo':'Mark reviewed in this demo'}</button>}</div></div></>:<div className="finding-placeholder"><span>↖</span><p>{scenario.description}<br/><b>As signals arrive, select a node or activity row to inspect its evidence.</b></p></div>}</div>
 <div className="agent-program"><div><p className="agent-mono">YOUR WHITE-LABEL CARE PROGRAM / SAMPLE DRAFT</p><h3>{company.trim()||'Your brand'} Care+</h3><p>{tick<6?'Evidence becomes a care program. Watch the agents connect each step.':tick<8?'Benefits agent is translating findings into a proposed care scope.':tick<10?'Brand and experience agents are assembling the customer journey.':'Your draft is ready to discuss with Hardsurance.'}</p><label>Your company<input maxLength={60} value={company} onChange={e=>setCompany(e.target.value)} /></label></div><div className="agent-deliverables">{['Hardware fault assessment','Repair coordination','Branded customer experience','Early-access project brief'].map((v,i)=><div key={v} className={tick>=i+7?'ready':''}><span>{tick>=i+7?'✓':'○'}</span>{v}<small>{tick>=i+7?'Drafted':'Preparing'}</small></div>)}{completed?<Link className="button primary" href="/#contact" onClick={handoff}>Discuss this care program ↗</Link>:<p className="fine-print">Continue the simulation to prepare your brief.</p>}</div></div>
 <div className="agent-terminal"><span className="terminal-dot"/><span>{completed?'COMPLETE':playing?'RUN':'PAUSED'}</span><p>{completed?'Sample care program prepared. Ready for your review.':tick>6?`${['benefits.agent → proposing care scope','brand.agent → applying your identity','experience.agent → preparing customer journey'][tick-7]||'handoff.agent → compiling project brief'}`:shown.length?`${shown[shown.length-1].agent} → ${shown[shown.length-1].label}`:'Waiting for the first sample signal…'}</p><span>00:{String(tick*3).padStart(2,'0')}</span></div>
 </div><p className="agent-disclosure">Interactive simulation with fictional records. No live telemetry, AI model calls or coverage decisions.</p></div></section>
}
