export type Finding = { id:string; label:string; short:string; agent:string; severity:'review'|'ready'|'watch'; signal:string; evidence:string; action:string; check:string; x:number; y:number };
export const agentScenarios: {id:string;name:string;asset:string;description:string;findings:Finding[]}[] = [
 {id:'robotics',name:'Warehouse robotics',asset:'Flower AMR / 24 sample units',description:'A motor fault, a software change and a service dependency. One connected picture.',findings:[
 {id:'motor',label:'Motor overheating',short:'MT',agent:'hardware.agent',severity:'review',signal:'Motor temperature exceeds the sample operating threshold.',evidence:'Sample telemetry: motor M-04 reached 92°C after 18 minutes. Ambient temperature remained 24°C.',action:'Route for technical diagnosis; assess whether the event fits a mechanical-fault benefit.',check:'Confirm operating conditions and maintenance history before a coverage review.',x:23,y:28},
 {id:'firmware',label:'Firmware change',short:'FW',agent:'software.agent',severity:'watch',signal:'The issue follows a new navigation release.',evidence:'Sample change log: navigation v3.8 deployed 35 minutes before the first motor alert.',action:'Link the release record to the service case; timing alone does not establish cause.',check:'Compare affected and unaffected units before attributing the fault.',x:73,y:23},
 {id:'sensor',label:'Sensor misalignment',short:'SN',agent:'diagnostics.agent',severity:'review',signal:'Repeated obstacle alerts correlate with hard stops.',evidence:'Sample event log: 16 false obstacle alerts on aisle 7; calibration record is missing.',action:'Request a calibration check and preserve the sensor event history.',check:'Verify calibration evidence and distinguish component failure from setup issues.',x:46,y:13},
 {id:'repair',label:'Repair dependency',short:'RP',agent:'service.agent',severity:'watch',signal:'A specialist motor module is needed for repair.',evidence:'Sample parts list: module M-04 requires an approved service partner. Stock has not been confirmed.',action:'Check partner capability and parts availability before promising a repair date.',check:'Require confirmation of parts and service capacity before scheduling.',x:79,y:66},
 {id:'record',label:'Asset record matched',short:'AR',agent:'asset.agent',severity:'ready',signal:'Serial, device model and sample program record align.',evidence:'Sample registry: FLW-004 matches Flower AMR and the illustrative FlowerCare configuration.',action:'Attach the verified sample asset record to the case.',check:'Match serial number and model to the program record.',x:24,y:74},
 {id:'terms',label:'Plan terms need review',short:'PT',agent:'plan.agent',severity:'review',signal:'The cause and applicable benefit remain unresolved.',evidence:'Sample plan: mechanical-fault benefit selected; diagnosis and eligibility review are still pending.',action:'Prepare a review packet instead of treating an alert as an approved claim.',check:'Require diagnosis, eligibility and final terms before any service commitment.',x:54,y:83},
 ]},
 {id:'field',name:'Field hardware',asset:'Field Scout / 12 sample devices',description:'Impact, environmental exposure and missing evidence—mapped before a service decision.',findings:[
 {id:'motor',label:'Impact detected',short:'IM',agent:'hardware.agent',severity:'review',signal:'A sample device records a sudden impact.',evidence:'Sample event record: a 3.2 g impact occurred during field deployment; the device then went offline.',action:'Collect an incident description and inspect physical damage.',check:'Separate observed damage from an inferred cause.',x:23,y:28},
 {id:'firmware',label:'Connectivity loss',short:'CN',agent:'software.agent',severity:'watch',signal:'The device stopped reporting after the incident.',evidence:'Sample telemetry: the final heartbeat arrived 8 seconds after the impact event.',action:'Check whether power, radio or network loss explains the missing data.',check:'Do not classify missing telemetry as total hardware loss.',x:73,y:23},
 {id:'sensor',label:'Moisture exposure',short:'ME',agent:'diagnostics.agent',severity:'review',signal:'An environmental sensor flags high humidity.',evidence:'Sample sensor reading: enclosure humidity reached 88%; seal condition is unknown.',action:'Request inspection evidence and compare use conditions with final eligibility rules.',check:'Verify enclosure and operating conditions before assigning a service route.',x:46,y:13},
 {id:'repair',label:'Remote recovery',short:'RC',agent:'service.agent',severity:'watch',signal:'The device needs collection from a remote site.',evidence:'Sample deployment record: access requires a site contact and collection arrangements.',action:'Coordinate a safe collection plan and confirm the service scope.',check:'Confirm location, contact and logistics before booking collection.',x:79,y:66},
 {id:'record',label:'Device identified',short:'ID',agent:'asset.agent',severity:'ready',signal:'The sample serial matches the device register.',evidence:'Sample registry: FLD-008 matches Field Scout; purchase record is attached.',action:'Keep asset evidence with the service request.',check:'Match device identity and purchase evidence.',x:24,y:74},
 {id:'terms',label:'Damage benefit review',short:'DB',agent:'plan.agent',severity:'review',signal:'Accidental damage is a selected sample benefit, not a claim approval.',evidence:'Sample configuration includes accidental damage; incident details and terms review are pending.',action:'Compile inspection and incident evidence for review.',check:'Review exclusions, eligibility and the cause of damage before a decision.',x:54,y:83},
 ]},
 {id:'compute',name:'AI infrastructure',asset:'Compute Station / 8 sample racks',description:'Cooling, power and component failures can share a cause. Trace the dependencies first.',findings:[
 {id:'motor',label:'Cooling interruption',short:'CL',agent:'hardware.agent',severity:'review',signal:'Cooling output falls below the sample baseline.',evidence:'Sample telemetry: cooling-loop output fell 32% while inlet temperature rose.',action:'Request cooling-system diagnosis and maintenance records.',check:'Verify the cooling failure path before selecting a repair scope.',x:23,y:28},
 {id:'firmware',label:'Power fluctuation',short:'PW',agent:'software.agent',severity:'watch',signal:'A voltage event overlaps with the thermal alert.',evidence:'Sample event log: a voltage deviation was recorded 14 seconds before the cooling alert.',action:'Correlate facility logs without assuming that timing proves causation.',check:'Compare power and equipment records to distinguish source from symptom.',x:73,y:23},
 {id:'sensor',label:'Thermal shutdown',short:'TS',agent:'diagnostics.agent',severity:'review',signal:'Two sample nodes enter protective shutdown.',evidence:'Sample host log: nodes C-02 and C-03 shut down after exceeding configured thermal limits.',action:'Inspect affected components and preserve shutdown evidence.',check:'Confirm component condition before considering repair or replacement.',x:46,y:13},
 {id:'repair',label:'Vendor handoff',short:'VH',agent:'service.agent',severity:'watch',signal:'Cooling and compute have different service owners.',evidence:'Sample service register lists separate specialists for the cooling loop and compute nodes.',action:'Assign an owner for each inspection and coordinate the handoff.',check:'Confirm responsibilities before scheduling dependent repairs.',x:79,y:66},
 {id:'record',label:'Inventory reconciled',short:'IR',agent:'asset.agent',severity:'ready',signal:'Affected sample components match the equipment register.',evidence:'Sample inventory: all three reported component serials match the site asset list.',action:'Attach the affected component list to the case.',check:'Match each component to its location and program record.',x:24,y:74},
 {id:'terms',label:'Scope boundary',short:'SB',agent:'plan.agent',severity:'review',signal:'Equipment care and business losses require separate consideration.',evidence:'Sample configuration concerns hardware service. Lost workload and business interruption are not assumed benefits.',action:'Make the scope boundary visible in the review packet.',check:'Do not imply business-loss protection from a hardware-care benefit.',x:54,y:83},
 ]}
];
