export const useCases={
 autonomous:{label:'Autonomous hardware',title:'Care for autonomous, AI-enabled systems.',description:'Autonomous platforms bring mechanical systems, sensing, compute and control software together. We are evaluating care requirements for these connected dependencies, from commissioning to service assessment.',film:'/films/autonomous-hardware.mp4',risks:['Platform, sensors and compute inventory','Operating domain and deployment conditions','Diagnostics, software versions and fault records','Specialist service and recovery requirements']},
 'ai-chips':{label:'Silicon & AI chips',title:'Care for silicon and compute components.',description:'From GPUs and AI accelerators to edge compute modules, silicon powers a new generation of machines. We’re exploring care for the physical hardware that makes intelligence possible.',film:'/films/ai-chips.mp4',risks:['Chip, board and system identification','Thermal and power conditions','Diagnostics and fault history','Manufacturer warranty and service options']},
 robotics:{label:'Robotics',title:'Care for deployed robotic systems.',description:'From warehouse robots to machines working alongside people, care should reflect the real deployment.',film:'/films/robot-chess.mp4',risks:['Machine and serial details','Operating environment','Fault and damage history','Repair and service records']},
 drones:{label:'Field hardware',title:'Care for hardware in the field.',description:'Drones, sensors and field devices work in changing environments. Help us shape care around those realities.',film:'/films/industrial-site.mp4',risks:['Device and payload details','Operating locations','Maintenance history','Service and recovery needs']},
 'data-centers':{label:'AI infrastructure',title:'Care for the hardware behind intelligence.',description:'Compute, cooling and connected equipment keep physical AI running. We’re exploring what a simpler care experience could look like.',film:'/films/data-center.mp4',risks:['Equipment inventory','Site and installation details','Component dependencies','Existing service agreements']},
 space:{label:'Frontier systems',title:'Care requirements for advanced systems.',description:'Advanced systems stretch the boundaries of hardware. We’re listening to builders to understand where better care can help.',film:'/films/orbital.mp4',risks:['System and component details','Testing environment','Specialist service needs','Lifecycle and handoff records']}
};
export const articles={
 'bvlos-policy-boundaries':{category:'Field hardware',title:'Start with the machine, not the paperwork.',dek:'The details that make a useful hardware care record.',sections:[['Know what you have','Start with a model, serial number, purchase record and a description of how the machine is used.'],['Keep the context','Operating conditions and maintenance history help explain an issue when it occurs.'],['Keep it together','A shared machine record gives your team one place to begin a service conversation.']]},
 'critical-infrastructure-dependencies':{category:'Hardware care',title:'A better service request starts before a fault.',dek:'Make the next conversation easier with a simple, consistent record.',sections:[['Record the baseline','Keep installation details, manuals and service contacts alongside the equipment record.'],['Describe the change','Capture when the issue started, what changed and any visible error messages.'],['Track the next step','Give each service request an owner and keep assessment updates with the machine.']]},
 'prelaunch-coverage':{category:'Physical AI',title:'Care should grow with your hardware.',dek:'From one machine to a fleet, continuity matters.',sections:[['Start small','A clear record for one machine is a useful foundation.'],['Keep handoffs visible','As equipment changes teams or locations, update its record and service contact.'],['Build for the lifecycle','Treat commissioning, maintenance and service as parts of the same hardware story.']]}
};
export type UseCaseSlug=keyof typeof useCases;
export type ArticleSlug=keyof typeof articles;
